name: grader_for_mashov_new
description: A new Flutter application.

publish_to: 'none'


version: 3.1.1+31

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  like_button: ^2.0.3
  wave: ^0.2.0
  page_transition: ^2.0.4
  wakelock: ^0.5.6
  flash: ^2.0.3
  url_launcher: ^6.0.12
  flutter_html: ^2.1.5 #no web
  shared_preferences: ^2.0.8
  charts_flutter: ^0.12.0
  open_file: ^3.2.1
  image_picker: ^0.8.4+4 #no web
  auto_size_text: ^3.0.0
  path_provider: ^2.0.6
  flutter_vibrate: ^1.3.0
  measured_size: ^1.0.0
  flutter_staggered_animations: ^1.0.0

  dio: ^4.0.1
  flutter_local_notifications: ^9.0.2
  permission_handler: ^8.2.5

  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/


  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-BoldItalic.ttf
          style: italic

    - family: Material Design Icons
      fonts:
        - asset: fonts/materialdesignicons-webfont.ttf
