name: grader_for_mashov_new
description: A new Flutter application.

publish_to: 'none'


version: 3.3.0+52

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  like_button: ^2.1.0
  wave: ^0.2.2
  page_transition: ^2.2.1
  wakelock_plus: ^1.4.0
  flash: ^3.1.1
  url_launcher: ^6.3.2
  flutter_html: ^3.0.0 #no web
  shared_preferences: ^2.5.3
  charts_flutter_new: ^0.12.0
  open_file: ^3.5.10
  image_picker: ^1.2.0 #no web
  auto_size_text: ^3.0.0
  path_provider: ^2.1.5
  platform: ^3.1.6
  flutter_vibrate: ^1.3.0
  measured_size: ^1.0.0
  flutter_staggered_animations: ^1.1.1

  dio: ^5.9.0
  flutter_local_notifications: ^19.4.2
  permission_handler: ^12.0.1

  #google_mobile_ads: ^1.0.1

  cupertino_icons: ^1.0.5
  file: ^7.0.1
  flutter_plugin_android_lifecycle: ^2.0.30

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/


  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-BoldItalic.ttf
          style: italic

    - family: Material Design Icons
      fonts:
        - asset: fonts/materialdesignicons-webfont.ttf
